apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "minimal-deploy.fullname" . }}
spec:
  rules:
    - host: example.your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "minimal-deploy.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
