global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'minimal-deploy-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
      
      
scrape_configs:
  - job_name: 'minimal-deploy-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
