apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-deploy-api
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: APP_ENV
          value: production
